version: "3.6"

services:
  dumpsc:
    container_name: dumpsc
    image: dumpsc:latest
    build:
      context: .
    volumes:
      - ./System:/System
      - ./Main.py:/Main.py
      - ./requirements.txt:/requirements.txt
      - ./Out-Sprites:/Out-Sprites
      - ./In-Compressed:/In-Compressed