version: "3.6"

services:
  dumpsc:
    container_name: dumpsc
    image: dumpsc:latest
    build:
      context: .
    volumes:
      - ./Out-Sprites:/Out-Sprites
      - ./In-Compressed:/In-Compressed